"""one_more_msg_tracking

Revision ID: 368e05ec9627
Revises: 43f11d78f2f3
Create Date: 2023-08-24 20:52:26.416312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368e05ec9627'
down_revision: Union[str, None] = '43f11d78f2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('playground_msg_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'playground_msg_id')
    # ### end Alembic commands ###
