"""sqd_msg_id added

Revision ID: 7ecda3839d58
Revises: 830233053717
Create Date: 2023-08-23 00:35:27.183899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ecda3839d58'
down_revision: Union[str, None] = '830233053717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sqd_msg_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sqd_msg_id')
    # ### end Alembic commands ###
