"""energy_refresh_added

Revision ID: 9b64b16dd3a9
Revises: 368e05ec9627
Create Date: 2023-08-25 16:10:18.467334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b64b16dd3a9'
down_revision: Union[str, None] = '368e05ec9627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_energy_refresh', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_energy_refresh')
    # ### end Alembic commands ###
