"""balance added

Revision ID: f97391b8c4ca
Revises: 3ba8499c6d44
Create Date: 2023-08-23 22:54:33.752954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97391b8c4ca'
down_revision: Union[str, None] = '3ba8499c6d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sqd_msg_id', new_column_name='sdq_msg_id')
    op.add_column('users', sa.Column('sdq_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sdq_msg_id', new_column_name='sqd_msg_id')
    op.drop_column('users', 'sdq_balance')
    # ### end Alembic commands ###
